import StoreContainer from '@/container/StoreContainer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <StoreContainer />
      {children}
    </>
  );
}