import { Gothic_A1, Noto_Serif_KR, ABeeZee } from 'next/font/google';
import './globals.css';
import Providers from '@/app/providers';
import Map3DWrapper from '@/container/Map3DWrapper';
import StoreContainer from '@/container/StoreContainer';
import InterviewContainer from '@/container/InterviewContainer';
import Navigation from '@/components/common/Navigation';
import AnimatedPanel from '@/components/common/AnimatedPanel';
import RootAnimation from '@/components/common/RootAnimation';

const gothic = Gothic_A1({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-gothic',
});
const noto = Noto_Serif_KR({
  weight: ['200', '300', '400', '500', '600', '700', '900'],
  subsets: ['latin'],
  variable: '--font-noto',
});
const abeezee = ABeeZee({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-abeezee',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`${gothic.variable} ${noto.variable} ${abeezee.variable}`}
      >
        <Providers>
          <Map3DWrapper />
          <StoreContainer />
          <Navigation />
          <AnimatedPanel baseRoute='interview' />
          <AnimatedPanel baseRoute='word' />
        </Providers>
      </body>
    </html>
  );
}
