import { Gothic_A1, Noto_Serif_KR } from 'next/font/google';
import './globals.css';
import Providers from '@/app/providers';
import Map3DWrapper from '@/container/Map3DWrapper';

const gothic = Gothic_A1({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-gothic',
});
const noto = Noto_Serif_KR({
  weight: ['200', '300', '400', '500', '600', '700', '900'],
  subsets: ['latin'],
  variable: '--font-noto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`${gothic.className} ${noto.className}`}
      >
        <Providers>
          <Map3DWrapper />
          {children}
        </Providers>
      </body>
    </html>
  );
}
